# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fe5b85dbc536b56b1557d1f6747b6bcc8962d79cb2618a1e9399926afe7aadbd97491afb4d7eb46ca090750908ae6341515435a061e88cc2c64961c572d395c

test:
  secret_key_base: 69a46328d2471a3d01ed621a27bb303ac95f13579edbb1467dc16bbb57bad728652e890daa07d104c9b05fb0de9cd5d8fa5e829c4d17fabf8dee908f58bff11f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
